### ISSUE TITLE
URLTable updates

### ISSUE THREAD

**Issue by optout2024** [ricko2001/RootsMagic_Database_Design#10]
Owner Type:
3 = Source,
4 = Citation,
5 = Place,
6 = Task,
14 = Place Details

OwnerID, link based on OwnerType:
3 = SourceTable.SourceID,
4 = CitationTable.CitationID, 
5 = PlaceTable.PlaceID,
6 = Tasktable.TaskID,
14 = PlaceTable.PlaceID

**Comment by ricko2001** [comment]
Updated the URLTable
Will add text to each file stating the possible OwnerTypes.
