### ISSUE TITLE
In the 'Notes' section of the NameTable doc, the row for the 'Sentence' field is duplicated.

### ISSUE THREAD

**Issue by optout2024** [ricko2001/RootsMagic_Database_Design#2]
In the 'Notes' section of the [NameTable doc](https://github.com/ricko2001/RootsMagic_Database_Design/blob/main/Tables/NameTable.md), the row for the 'Sentence' field is duplicated.

**Comment by ricko2001** [comment]
Fixed. Thanks for reporting it.
