### ISSUE TITLE
NameTable question - can each name have a dif B & D date in the index?"

### ISSUE THREAD

**Issue by optout2024** [ricko2001/RootsMagic_Database_Design#4]
You ask: "De-normalized Birth and death dates should go in the PersonTable. A person can have multiple names, can each name have a dif B & D date in the index?"

In my testing the answer is no. Changing either the date or the primary flag for a birth or death Fact changes the index date for all names/alt names. 

The is also true with the issue related to wrong dates in the index. This occur when a person has 2 birth or death Facts with different dates and the primary birth or death fact gets deleted. The remaining birth fact becomes primary but the index is not updated with the new date,. While the dates shown in the index are no longer correct, they remain consistent across all names for a person.

**Comment by ricko2001** [comment]
Probably the main use of the b&d dates in the names table is for the names index. So I guess it keeps the data together,

These seem to get out of synch fairly often based on user posts in user groups.

**Comment by ricko2001** [comment]
Thanks for testing this
