### ISSUE TITLE
Ancestry table updates

### ISSUE THREAD

**Issue by optout2024** [ricko2001/RootsMagic_Database_Design#6]
Here are the updates from review of the ancestrytable.
anID note = 
Person = [d]{12}:[d}{4}:[d]{9} - e.g.: 121212121212:1030:123456789,
Citation, origin RM= [d]:9000:[d]  (length varies),
Citation, origin Ancestry = [d]:[d]  (length varies depending upon Ancestry collection),
Media = Ancestry assigned ID (matches filename for media downloaded from Ancestry)

Modified = 
For LinkType=0 (Person):
0 = No modification detected, 
1 = Change identified in RM db or in Ancestry via Treeshare notification. Person’s status appears as changed in Treeshare.

anVersion = 
Hex code where LinkType=0 (Person), 
Otherwise NULL

**Comment by optout2024** [comment]
I meant to ask this question. You note that "localeID 1030 = English-USA", which makes sense but how did you figure that out?

**Comment by ricko2001** [comment]
Oops. Another error
https://wiki.freepascal.org/Language_Codes

1030 is danish
Eng is 1033

**Comment by ricko2001** [comment]
I removed the erroneous line. Still no new progress on the AncestryTable.
